version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gpt-front
    env_file:
      - .env
    expose:
      - 5543
    networks:
      - proxy
networks:
  proxy:
    external: true